name: list all changed files

on:
  pull_request:
		types: 
			[closed]
		paths:
			- 'schemas/**'
    branches:
      - main

jobs:
  if_merged:
		if: contains(github.event.pull_request.labels.*.name, 'Update')		
		steps:
			- name: Checkout code
      	uses: actions/checkout@v2
			
			- name: Changed files
				id: changed-files
				uses: tj-actions/changed-files@v17.3
				with:
          format: space-delimited

      - name: Print all changed files
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}