name: list-changed-files

on:
  pull_request:
    types:
      - closed
    paths:
      - 'schemas/**.json'
    branches:
      - main

jobs:
  registry_upload:
		name: upload to schemas registry
    if: github.event.pull_request.merged == true
		runs-on: ubuntu-latest
		steps:
			- name: Checkout code
        uses: actions/checkout@v2
			
			- name: Changed files
				id: changed-files
				uses: tj-actions/changed-files@17.3
				with:
          format: space-delimited

			- name: List changed files
				run: |
					for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
						echo ${{file}}
					done